### ISSUE TITLE
Invalid page URL

### ISSUE THREAD

**Issue by Steve0Greatness** [mp-pinheiro/nekoweb-deploy#10]
Hey there! I'm currently seeing the following error when attempting to push to my Nekoweb website
``
{'message': 'One or more errors occurred during deployment', 'error': 'Invalid page URL: `https://steve0greatness.nekoweb.org`./ Check your `NEKOWEB_PAGENAME` parameter.', 'details': None, 'advice': 'Please check NekoWeb as the state of the website might be corrupted. Consider downloading the build artifact and manually uploading the zip file as a workaround. You can also open an issue on the `mp-pinheiro/nekoweb-deploy` Github repository if needed.'}
``
I've tried rerunning it, and even checked if the API key was wrong. Note that before the request to clean up my final directory had went through.

**Comment by mp-pinheiro** [comment]
hey! can you share your action yml file?

**Comment by Steve0Greatness** [comment]
Yeah sure

[Original URL](https://github.com/Steve0Greatness/steve0greatness.github.io/blob/main/.github/workflows/build-deploy.yml)
```yaml
name: Build and Deploy site to Nekoweb

on:
  push:
    branches: [ "main" ]

permissions: 
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: [ "3.12" ]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Python dependencies
              uses: py-actions/py-dependency-install@v4
              with:
                path: "requirements.txt"
            - name: Pull Changes
              run: |
                git pull
            - name: Build Site
              run: python build.py
            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                path: build
    deploy:
      if: "contains(github.event.head_commit.message, '!action/build-deploy')"
      needs: [build]
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [ "3.12" ]
      steps:
        - uses: actions/checkout@v4
        - name: Download build results
          uses: actions/download-artifact@v4
        - name: Deploy to Nekoweb
          uses: mp-pinheiro/nekoweb-deploy@main
          with:
            API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
            BUILD_DIR: "/home/runner/work/WikiGen/WikiGen/artifact"
            DEPLOY_DIR: "/build"
            CLEANUP: "True"
            DELAY: "0.5"
            NEKOWEB_PAGENAME: "steve0greatness"
```
