### ISSUE TITLE
Keep getting Error: Missing argument 'NEKOWEB_PAGENAME'. Error: Process completed with exit code 2.

### ISSUE THREAD

**Issue by strawberrysnails** [mp-pinheiro/nekoweb-deploy#9]
Not sure what I did wrong but I keep getting the above mentioned error. 

I'm wondering if it has to do with my file paths. I'm using 11ty and my build is under /public. I have the same folder name on nekoweb too. 

You can see the repo for my nekoweb if that helps [here](https://github.com/leajpg/snails-website)

```
name: Deploy to Nekoweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build
        run: |
          mkdir -p ./build
          cp -r ./public/* ./build

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@main
        with:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          BUILD_DIR: "./build"
          DEPLOY_DIR: "/"
          CLEANUP: "true"
          DELAY: "0.5"
          NEKOWEB_PAGENAME: "snails"

```
